Update README.md
nodejs/node-gyp pull request #2213
Opened 2020-09-02 16:52 UTC by enes4949

Not running npm install -g node-gyp as root/admin gives permission error.

##### Checklist

- [ ] `npm install && npm test` passes
- [ ] tests are included 
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

##### Description of change

2020-09-03 01:59 UTC, rvagg requested changes
You need a space before `(` and this isn't quite correct - many people (myself included) will set up their system so that their global node_modules is owned by their regular dev user account so `sudo` never needs to get involved. I'm not comfortable recommending root or `sudo` usage, although a suggestion about permissions and the need to overcome these problems might be welcome.

Something like:

> If your user account doesn't have access to the global `node_modules` (recommended) then this may need to be run as the root user or with `sudo`.

2020-09-03 02:00 UTC, rvagg commented on README.md
> -$ npm install -g node-gyp
also this change should be reverted or you're going to need to do it for all of the bash blocks in the README (which I'm not opposed to)

2021-03-26 12:05 UTC, cclauss commented on README.md
> +Install all the required tools and configurations using Microsoft's [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) using `npm install --global windows-build-tools` from
Does windows-build-tools still install legacy Python?  If so then it should be removed in favor of installing Python 3 from the Microsoft App Store.

2021-06-22 05:27 UTC, cclauss commented
Closing.  Out of sync with the current README.md.

2021-06-22 05:27 UTC, closed without merging