feat: promisify remove
nodejs/node-gyp pull request #2225
Opened 2020-09-19 18:58 UTC by imatlopez

##### Checklist

- [ ] `npm install && npm test` passes
- [ ] tests are included 
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

##### Description of change

An effort to modernize the code

2020-11-02 13:30 UTC, blindmanyo22 approved these changes

2020-11-02 13:33 UTC, cclauss commented on .github/workflows/tests.yml
> +        python: [3.6, 3.7, 3.8]
```suggestion
        python: [3.6, 3.7, 3.8, 3.9]
```

2020-11-02 13:35 UTC, cclauss requested changes
Please resolve the conflicts and also ensure that we are testing on Python 3.9.

2021-04-01 05:37 UTC, cclauss reviewed
RSLGTM

2023-06-20 13:44 UTC, closed without merging