Chore: Refactor Multiple Functions 🧷
nodejs/node-gyp pull request #2554
Opened 2021-11-20 15:15 UTC by yezz123

##### Checklist

- [x] `npm install && npm test` passes
- [ ] tests are included 
- [ ] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/googleapis/release-please#how-should-i-write-my-commits)

##### Description of change

This is just a refactoring for multiple functions in the Python codebase, just to let its many multiple changes in the PEP rules and guidelines. Any Issue I'm here to discuss 🚀

2021-11-20 16:08 UTC, cclauss requested changes

2021-11-20 16:08 UTC, cclauss commented on gyp/tools/pretty_gyp.py
> +                if brace_diff == 0:
I do not see an advantage to risking this change.

Unless of course, we have pytests that cover all cases.

2021-11-20 17:12 UTC, richardlau requested changes
These need to be made in the upstream https://github.com/nodejs/gyp-nex repository.

2021-11-21 22:45 UTC, yezz123 commented
> These need to be made in the upstream https://github.com/nodejs/gyp-next repository.

If this merged here I can open another PR in the Upstream Repository.

2021-11-22 08:21 UTC, rvagg commented
@yezz123 sorry, no, we pull from that repo to here - we even have a script to do it in the project root. But maybe now that you've made the changes here you can copy the files over the top of a clone of gyp-next, we may be in sync with the current version already so it might not be too painful. Thanks for the contribution though!

2021-11-22 08:21 UTC, closed without merging